### ISSUE TITLE
Random crashes when deploying application

### ISSUE THREAD

**Issue by ndbroadbent** [sj26/sidekiq-cloudwatchmetrics#41]
I'm seeing some random crashes in production when I deploy my app. It only seems to happen for a few of my puma containers, and they are all able to start eventually without crashing. I'm getting the error: "ArgumentError: expected :endpoint to be a HTTP or HTTPS endpoint"

```
2023-09-28T00:05:57Z service/web/web-79df44bcbd-jw2hx 00:05:57 web.1     | [131] ! Unable to load application: ArgumentError: expected :endpoint to be a HTTP or HTTPS endpoint
2023-09-28T00:05:57Z service/web/web-79df44bcbd-jw2hx 00:05:57 web.1     | 	from /usr/local/bundle/ruby/2.7.0/gems/aws-sdk-core-3.178.0/lib/seahorse/client/base.rb:81:in `block in after_initialize'
2023-09-28T00:05:57Z service/web/web-79df44bcbd-jw2hx 00:05:57 web.1     | /usr/local/bundle/ruby/2.7.0/gems/aws-sdk-core-3.178.0/lib/seahorse/client/plugins/endpoint.rb:39:in `after_initialize': expected :endpoint to be a HTTP or HTTPS endpoint (ArgumentError)
2023-09-28T00:05:57Z service/web/web-79df44bcbd-jw2hx 00:05:57 web.1     | bundler: failed to load command: puma (/usr/local/bundle/ruby/2.7.0/bin/puma)
2023-09-28T00:05:57Z service/web/web-79df44bcbd-jw2hx 00:05:57 web.1     | 	from /usr/local/bundle/ruby/2.7.0/gems/aws-sdk-core-3.178.0/lib/seahorse/client/base.rb:80:in `each'
2023-09-28T00:05:57Z service/web/web-79df44bcbd-jw2hx 00:05:57 web.1     | 	from /usr/local/bundle/ruby/2.7.0/gems/aws-sdk-core-3.178.0/lib/seahorse/client/base.rb:80:in `after_initialize'
2023-09-28T00:05:57Z service/web/web-79df44bcbd-jw2hx 00:05:57 web.1     | 	from /usr/local/bundle/ruby/2.7.0/gems/aws-sdk-core-3.178.0/lib/seahorse/client/base.rb:24:in `initialize'
2023-09-28T00:05:57Z service/web/web-79df44bcbd-jw2hx 00:05:57 web.1     | 	from /usr/local/bundle/ruby/2.7.0/gems/aws-sdk-cloudwatch-1.78.0/lib/aws-sdk-cloudwatch/client.rb:386:in `initialize'
2023-09-28T00:05:57Z service/web/web-79df44bcbd-jw2hx 00:05:57 web.1     | 	from /usr/local/bundle/ruby/2.7.0/gems/aws-sdk-core-3.178.0/lib/seahorse/client/base.rb:102:in `new'
2023-09-28T00:05:57Z service/web/web-79df44bcbd-jw2hx 00:05:57 web.1     | 	from /app/config/initializers/_sidekiq.rb:94:in `<main>'
2023-09-28T00:05:57Z service/web/web-79df44bcbd-jw2hx 00:05:57 web.1     | 	from /usr/local/bundle/ruby/2.7.0/gems/bootsnap-1.4.8/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:59:in `load'
2023-09-28T00:05:57Z service/web/web-79df44bcbd-jw2hx 00:05:57 web.1     | 	from /usr/local/bundle/ruby/2.7.0/gems/bootsnap-1.4.8/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:59:in `load'
2023-09-28T00:05:57Z service/web/web-79df44bcbd-jw2hx 00:05:57 web.1     | 	from /usr/local/bundle/ruby/2.7.0/gems/activesupport-6.1.7.6/lib/active_support/dependencies.rb:326:in `block in load'
```

This is my code in `config/initializers/_sidekiq.rb`:

```
if ENV['AWS_CLOUDWATCH_ACCESS_KEY_ID'].present? &&
   ENV['AWS_CLOUDWATCH_ACCESS_KEY_SECRET'].present? &&
   ENV['AWS_CLOUDWATCH_REGION'].present?
  require 'sidekiq/cloudwatchmetrics'
  # Send Sidekiq job metrics to AWS CloudwWtch (used for autoscaling in Convox)
  # https://github.com/sj26/sidekiq-cloudwatchmetrics
  # IAM Role: https://docs.aws.amazon.com/AmazonCloudWatch/latest/monitoring/create-iam-roles-for-cloudwatch-agent-commandline.html
  # Role: CloudWatchAgentServerPolicy
  cloudwatch_client = Aws::CloudWatch::Client.new(
    region: ENV.fetch('AWS_CLOUDWATCH_REGION', nil),
    credentials: Aws::Credentials.new(
      ENV.fetch('AWS_CLOUDWATCH_ACCESS_KEY_ID', nil),
      ENV.fetch('AWS_CLOUDWATCH_ACCESS_KEY_SECRET', nil)
    )
  )
  Sidekiq::CloudWatchMetrics.enable!(
    client: cloudwatch_client,
    namespace: ENV['AWS_CLOUDWATCH_SIDEKIQ_NAMESPACE'] || 'Sidekiq'
  )
end
```

There's some kind of weird race condition that I can't figure out. I don't really understand why it crashes and then succeeds later when restarting the container.

It's crashing in this method:

```

        def after_initialize(client)
          endpoint = client.config.endpoint
          if endpoint.nil?
            msg = "missing required option `:endpoint'"
            raise ArgumentError, msg
          end

          endpoint = URI.parse(endpoint.to_s)
          if URI::HTTPS === endpoint or URI::HTTP === endpoint
            client.config.endpoint = endpoint
          else
            msg = 'expected :endpoint to be a HTTP or HTTPS endpoint'
            raise ArgumentError, msg
          end
        end
```

If I step through it manually on my local machine:

```
[2] pry(main)> cloudwatch_client.config.endpoint
#<URI::HTTPS https://monitoring.us-east-1.amazonaws.com>
[3] pry(main)> endpoint = URI.parse(cloudwatch_client.config.endpoint.to_s)
#<URI::HTTPS https://monitoring.us-east-1.amazonaws.com>
[4] pry(main)> URI::HTTPS === endpoint
true
```

It's very confusing. If my `AWS_CLOUDWATCH_REGION` env var is unset or an empty string then this code doesn't run at all. 

I'll deploy this change and see if I can get some more info:

```
begin
    cloudwatch_client = Aws::CloudWatch::Client.new(
      region: ENV.fetch('AWS_CLOUDWATCH_REGION', nil),
      credentials: Aws::Credentials.new(
        ENV.fetch('AWS_CLOUDWATCH_ACCESS_KEY_ID', nil),
        ENV.fetch('AWS_CLOUDWATCH_ACCESS_KEY_SECRET', nil)
      )
    )
    Sidekiq::CloudWatchMetrics.enable!(
      client: cloudwatch_client,
      namespace: ENV['AWS_CLOUDWATCH_SIDEKIQ_NAMESPACE'] || 'Sidekiq'
    )
  rescue ArgumentError => e
    Rails.logger.info("Error enabling Sidekiq::CloudWatchMetrics: #{e.message}")
    Sentry.capture_exception(e)

    endpoint = cloudwatch_client.config.endpoint
    Sentry.capture_message("CloudWatch endpoint causing error: '#{endpoint}'")
  end
```

**Comment by sj26** [comment]
It sounds like this error is being raised within the construction of the client. You might need help from aws-sdk.

I'd be looking into whether it's using instance meta-data, and if that endpoint is flaky for some of your instances.

**Comment by ndbroadbent** [comment]
Ah I see, thanks! I'll keep investigating and see if I can figure out what's causing it.

**Comment by ndbroadbent** [comment]
This is bizarre:

```
2023-09-28T00:35:59Z service/worker/worker-7496dfbfd8-vz6pd 00:35:59 worker.1  | 2023-09-28T00:35:59.523Z pid=19 tid=7vb INFO: Sidekiq 7.1.4 connecting to Redis with options {:size=>3, :pool_name=>"default", :url=>"redis://prrpwibyfnis0k5.cp5pt0.ng.0001.use1.cache.amazonaws.com:6379/0", :id=>nil, :reconnect_attempts=>[0, 0.1, 0.5, 1, 3, 5, 5, 5, 5, 5]}
2023-09-28T00:36:00Z service/web/web-79df44bcbd-jm55k 00:36:00 web.1     | I, [2023-09-28T00:36:00.704433 #95]  INFO -- sentry: [Transport] Sending envelope with items [sessions]  to Sentry
2023-09-28T00:36:02Z service/web/web-5485c9f444-fjldw 00:36:02 web.1     | I, [2023-09-28T00:36:02.872591 #20]  INFO -- : [SKYLIGHT] [5.3.4] Skylight agent enabled
2023-09-28T00:36:03Z service/web/web-5485c9f444-fjldw 00:36:03 web.1     | I, [2023-09-28T00:36:03.129005 #20]  INFO -- : Error enabling Sidekiq::CloudWatchMetrics: expected :endpoint to be a HTTP or HTTPS endpoint
2023-09-28T00:36:03Z service/web/web-5485c9f444-fjldw 00:36:03 web.1     | I, [2023-09-28T00:36:03.220977 #20]  INFO -- sentry: [Transport] Sending envelope with items [event] 46aba68de0174c97a1640471f350b26f to Sentry
2023-09-28T00:36:03Z service/web/web-5485c9f444-fjldw 00:36:03 web.1     | I, [2023-09-28T00:36:03.228238 #20]  INFO -- sentry: [Transport] Sending envelope with items [event] 96ea40719011439b931b5afe232a6c93 to Sentry
2023-09-28T00:36:03Z service/web/web-5485c9f444-fjldw 00:36:03 web.1     | I, [2023-09-28T00:36:03.234199 #20]  INFO -- : Sending emails with Postmark
2023-09-28T00:36:03Z service/web/web-5485c9f444-fjldw 00:36:03 web.1     | E, [2023-09-28T00:36:03.337606 #20] ERROR -- sentry: Event sending failed: SSL_connect returned=1 errno=0 state=error: wrong version number
2023-09-28T00:36:03Z service/web/web-5485c9f444-fjldw 00:36:03 web.1     | I, [2023-09-28T00:36:03.340125 #20]  INFO -- sentry: Unreported Event: ArgumentError: expected :endpoint to be a HTTP or HTTPS endpoint
2023-09-28T00:36:03Z service/web/web-5485c9f444-fjldw 00:36:03 web.1     | E, [2023-09-28T00:36:03.340269 #20] ERROR -- sentry: exception happened in background worker: SSL_connect returned=1 errno=0 state=error: wrong version number
2023-09-28T00:36:03Z service/web/web-5485c9f444-fjldw 00:36:03 web.1     | E, [2023-09-28T00:36:03.355669 #20] ERROR -- sentry: exception happened in background worker: SSL_connect returned=1 errno=0 state=error: wrong version number
2023-09-28T00:36:03Z service/web/web-5485c9f444-fjldw 00:36:03 web.1     | I, [2023-09-28T00:36:03.355543 #20]  INFO -- sentry: Unreported Event: cloudwatch_client present?: false
2023-09-28T00:36:03Z service/web/web-5485c9f444-fjldw 00:36:03 web.1     | CloudWatch config endpoint: ''
2023-09-28T00:36:03Z service/web/web-5485c9f444-fjldw 00:36:03 web.1     | E, [2023-09-28T00:36:03.353542 #20] ERROR -- sentry: Event sending failed: SSL_connect returned=1 errno=0 state=error: wrong version number
2023-09-28T00:36:03Z service/web/web-5485c9f444-fjldw 00:36:03 web.1     | AWS_CLOUDWATCH_REGION: 'us-east-1'
2023-09-28T00:36:03Z service/web/web-5485c9f444-fjldw 00:36:03 web.1     | AWS_CLOUDWATCH_ACCESS_KEY_SECRET present?: true
2023-09-28T00:36:03Z service/web/web-5485c9f444-fjldw 00:36:03 web.1     | AWS_CLOUDWATCH_ACCESS_KEY_ID: '............'
2023-09-28T00:36:03Z service/web/web-5485c9f444-fjldw 00:36:03 web.1     | I, [2023-09-28T00:36:03.733706 #20]  INFO -- : [Shrine] Using AWS S3 storage (region: us-east-1, bucket: ....)
2023-09-28T00:36:03Z service/web/web-5485c9f444-fjldw 00:36:03 web.1     | [20] ! Unable to load application: ArgumentError: expected :endpoint to be a HTTP or HTTPS endpoint
2023-09-28T00:36:03Z service/web/web-5485c9f444-fjldw 00:36:03 web.1     | bundler: failed to load command: puma (/usr/local/bundle/ruby/2.7.0/bin/puma)
2023-09-28T00:36:03Z service/web/web-5485c9f444-fjldw 00:36:03 web.1     | /usr/local/bundle/ruby/2.7.0/gems/aws-sdk-core-3.178.0/lib/seahorse/client/plugins/endpoint.rb:39:in `after_initialize': expected :endpoint to be a HTTP or HTTPS endpoint (ArgumentError)
2023-09-28T00:36:03Z service/web/web-5485c9f444-fjldw 00:36:03 web.1     | 	from /usr/local/bundle/ruby/2.7.0/gems/aws-sdk-core-3.178.0/lib/seahorse/client/base.rb:81:in `block in after_initialize'
2023-09-28T00:36:03Z service/web/web-5485c9f444-fjldw 00:36:03 web.1     | 	from /usr/local/bundle/ruby/2.7.0/gems/aws-sdk-core-3.178.0/lib/seahorse/client/base.rb:80:in `each'
2023-09-28T00:36:03Z service/web/web-5485c9f444-fjldw 00:36:03 web.1     | 	from 
...
```

Something very strange is happening here. It's not just killing CloudWatch, it's also preventing me from sending error reports to Sentry. I wonder if it could be related to the version of the `uri` gem in my Gemfile. But it's strange that it's not deterministic and happens randomly.

Anyway, I just thought I should post here in case someone else runs into a similar issue, so it shows up on Google. But sorry it's not really related to this gem!

**Comment by sj26** [comment]
Very weird! Sorry it's being such a pain 😔
